POST http://localhost:7200/api/reservations
content-type: application/json

{
  "foodTruck": "Burger Beast",
  "timeRange": {
    "start": "2025-06-01T18:15:12.113Z",
    "end": "2025-06-04T18:15:12.113Z"
  },
  "customerName": "asdasd",
  "expectedGuests": 2
}